const UsersType = {
    SIGNUP_USER: 'SIGNUP_USER',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',

    SIGNIN_USER: 'SIGNIN_USER',
    SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
    SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',

    SIGNOUT_USER: 'SIGNOUT_USER',
    SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
    SIGNOUT_USER_FAILURE: 'SIGNOUT_USER_FAILURE',
};

const Types = {
    ...UsersType,
};

export default Types;
